export const PIANO_SOUNDS: Record<string, number> = {
  'C4': require('../assets/sounds/c4.wav'),
  'C#4': require('../assets/sounds/csharp4.wav'),
  'D4': require('../assets/sounds/d4.wav'),
  'D#4': require('../assets/sounds/dsharp4.wav'),
  'E4': require('../assets/sounds/e4.wav'),
  'F4': require('../assets/sounds/f4.wav'),
  'F#4': require('../assets/sounds/fsharp4.wav'),
  'G4': require('../assets/sounds/g4.wav'),
  'G#4': require('../assets/sounds/gsharp4.wav'),
  'A4': require('../assets/sounds/a4.wav'),
  'A#4': require('../assets/sounds/asharp4.wav'),
  'B4': require('../assets/sounds/b4.wav'),
  'C5': require('../assets/sounds/c5.wav'),
  'C#5': require('../assets/sounds/csharp5.wav'),
  'D5': require('../assets/sounds/d5.wav'),
  'D#5': require('../assets/sounds/dsharp5.wav'),
  'E5': require('../assets/sounds/e5.wav'),
  'F5': require('../assets/sounds/f5.wav'),
  'F#5': require('../assets/sounds/fsharp5.wav'),
  'G5': require('../assets/sounds/g5.wav'),
  'G#5': require('../assets/sounds/gsharp5.wav'),
  'A5': require('../assets/sounds/a5.wav'),
  'A#5': require('../assets/sounds/asharp5.wav'),
  'B5': require('../assets/sounds/b5.wav'),
  'C6': require('../assets/sounds/c6.wav'),
};
